import { Problem } from "@yema/shared";

export const problemSeeds: Problem[] = [
  {
    id: "login-card",
    title: "实现登录卡片页面",
    difficulty: "easy",
    shortDescription: "实现一个居中的登录卡片，包含标题、两个输入框和一个提交按钮。",
    description:
      "请完成一个登录卡片页面。页面中至少要有主标题、用户名输入框、密码输入框和登录按钮，并保持基础的居中布局与清晰层次。",
    templateFiles: [
      {
        path: "index.html",
        language: "html",
        content:
          "<!DOCTYPE html>\n<html lang=\"zh-CN\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>登录卡片</title>\n    <link rel=\"stylesheet\" href=\"styles.css\" />\n  </head>\n  <body>\n    <main class=\"page\">\n      <section class=\"card\" id=\"login-card\">\n        <h1>欢迎回来</h1>\n        <form class=\"form\">\n          <input type=\"text\" placeholder=\"用户名\" />\n          <input type=\"password\" placeholder=\"密码\" />\n          <button type=\"submit\">立即登录</button>\n        </form>\n      </section>\n    </main>\n  </body>\n</html>\n",
      },
      {
        path: "styles.css",
        language: "css",
        content:
          "body {\n  margin: 0;\n  font-family: Arial, sans-serif;\n  background: linear-gradient(135deg, #f4efe6, #d7e4f3);\n}\n\n.page {\n  min-height: 100vh;\n  display: grid;\n  place-items: center;\n}\n\n.card {\n  width: 320px;\n  padding: 24px;\n  border-radius: 18px;\n  background: rgba(255, 255, 255, 0.92);\n  box-shadow: 0 18px 40px rgba(24, 39, 75, 0.16);\n}\n\n.form {\n  display: grid;\n  gap: 12px;\n}\n",
      },
    ],
    config: {
      editableFiles: [
        {
          path: "index.html",
          language: "html",
          content:
            "<!DOCTYPE html>\n<html lang=\"zh-CN\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>登录卡片</title>\n    <link rel=\"stylesheet\" href=\"styles.css\" />\n  </head>\n  <body>\n    <main class=\"page\">\n      <section class=\"card\" id=\"login-card\">\n        <h1>欢迎回来</h1>\n        <form class=\"form\">\n          <input type=\"text\" placeholder=\"用户名\" />\n          <input type=\"password\" placeholder=\"密码\" />\n          <button type=\"submit\">立即登录</button>\n        </form>\n      </section>\n    </main>\n  </body>\n</html>\n",
        },
        {
          path: "styles.css",
          language: "css",
          content:
            "body {\n  margin: 0;\n  font-family: Arial, sans-serif;\n  background: linear-gradient(135deg, #f4efe6, #d7e4f3);\n}\n\n.page {\n  min-height: 100vh;\n  display: grid;\n  place-items: center;\n}\n\n.card {\n  width: 320px;\n  padding: 24px;\n  border-radius: 18px;\n  background: rgba(255, 255, 255, 0.92);\n  box-shadow: 0 18px 40px rgba(24, 39, 75, 0.16);\n}\n\n.form {\n  display: grid;\n  gap: 12px;\n}\n",
        },
      ],
      requirements: [
        "页面中包含登录标题、用户名输入框、密码输入框和提交按钮。",
        "登录卡片在桌面视口下应保持明显的居中展示。",
        "表单元素之间应有基本的间距与层次。",
      ],
      requiredSelectors: ["#login-card", ".form", "button"],
      requiredTexts: ["欢迎回来", "立即登录"],
      evaluationRules: [
        {
          id: "login-required-file-html",
          title: "保留 HTML 入口文件",
          description: "提交中需要包含 index.html，保证页面可被评测系统加载。",
          engine: "static",
          type: "file",
          dimension: "engineering",
          target: "index.html",
          failureSeverity: "error",
          failureScoreImpact: -10,
          successMessage: "已找到 index.html，可继续进行结构与渲染检查。",
          failureMessage: "缺少 index.html，评测系统无法定位页面入口。",
        },
        {
          id: "login-required-file-css",
          title: "保留样式文件",
          description: "提交中需要包含 styles.css，以便评估页面样式和布局。",
          engine: "static",
          type: "file",
          dimension: "engineering",
          target: "styles.css",
          failureSeverity: "error",
          failureScoreImpact: -8,
          successMessage: "已找到 styles.css，样式检查可正常进行。",
          failureMessage: "缺少 styles.css，页面样式和布局将无法完整评估。",
        },
        {
          id: "login-selector-card",
          title: "存在登录卡片容器",
          description: "源码中应存在 id 为 login-card 的卡片容器。",
          engine: "static",
          type: "selector",
          dimension: "correctness",
          target: "#login-card",
          failureSeverity: "warning",
          failureScoreImpact: -8,
          successMessage: "源码中已包含登录卡片容器。",
          failureMessage: "源码中未找到 #login-card，页面主体结构不完整。",
        },
        {
          id: "login-selector-form",
          title: "存在表单容器",
          description: "源码中应包含表单容器，便于组织输入项和按钮。",
          engine: "static",
          type: "selector",
          dimension: "correctness",
          target: ".form",
          failureSeverity: "warning",
          failureScoreImpact: -6,
          successMessage: "源码中已包含表单容器。",
          failureMessage: "源码中未找到 .form，输入区结构不够清晰。",
        },
        {
          id: "login-text-title",
          title: "显示欢迎标题",
          description: "页面中应出现“欢迎回来”文字。",
          engine: "render",
          type: "text",
          dimension: "uiRendering",
          target: "欢迎回来",
          failureSeverity: "warning",
          failureScoreImpact: -6,
          successMessage: "页面渲染后已显示欢迎标题。",
          failureMessage: "页面渲染后未显示“欢迎回来”标题。",
        },
        {
          id: "login-text-button",
          title: "显示登录按钮文案",
          description: "页面中应出现“立即登录”按钮文案。",
          engine: "render",
          type: "text",
          dimension: "correctness",
          target: "立即登录",
          failureSeverity: "warning",
          failureScoreImpact: -6,
          successMessage: "页面渲染后已显示登录按钮文案。",
          failureMessage: "页面渲染后未显示“立即登录”按钮文案。",
        },
        {
          id: "login-render-button",
          title: "浏览器中存在按钮元素",
          description: "渲染后的 DOM 中应存在按钮元素。",
          engine: "render",
          type: "selector",
          dimension: "uiRendering",
          target: "button",
          failureSeverity: "warning",
          failureScoreImpact: -6,
          successMessage: "浏览器渲染后的 DOM 中已检测到按钮元素。",
          failureMessage: "浏览器渲染后的 DOM 中未检测到按钮元素。",
        },
        {
          id: "login-layout-keyword",
          title: "包含基础居中布局样式",
          description: "样式中建议体现基础布局能力，例如 display/grid/flex。",
          engine: "static",
          type: "keyword",
          dimension: "codeQuality",
          keywords: ["display", "place-items"],
          failureSeverity: "warning",
          failureScoreImpact: -6,
          successMessage: "样式中已包含基础布局声明。",
          failureMessage: "样式中缺少明确的布局声明，页面可能难以稳定居中。",
        },
        {
          id: "login-console-clean",
          title: "浏览器运行期无报错",
          description: "页面加载后不应出现 console error 或 page error。",
          engine: "render",
          type: "console",
          dimension: "engineering",
          failureSeverity: "warning",
          failureScoreImpact: -6,
          successMessage: "浏览器控制台未捕获到运行期错误。",
          failureMessage: "浏览器控制台存在运行期错误，说明页面稳定性仍需提升。",
        },
      ],
      renderConfig: {
        viewportWidth: 1440,
        viewportHeight: 960,
        waitAfterLoadMs: 250,
      },
      weights: {
        correctness: 35,
        codeQuality: 20,
        uiRendering: 25,
        engineering: 20,
      },
    },
  },
  {
    id: "todo-board",
    title: "实现待办事项面板",
    difficulty: "medium",
    shortDescription: "实现一个待办事项面板，包含输入区、添加按钮和任务列表。",
    description:
      "请完成一个简洁的待办事项面板。页面中至少要有标题、输入框、添加按钮和列表区域，并保持基本的卡片式排版。",
    templateFiles: [
      {
        path: "index.html",
        language: "html",
        content:
          "<!DOCTYPE html>\n<html lang=\"zh-CN\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>待办事项面板</title>\n    <link rel=\"stylesheet\" href=\"styles.css\" />\n  </head>\n  <body>\n    <main class=\"todo-page\">\n      <section class=\"todo-card\">\n        <h1>待办事项</h1>\n        <div class=\"composer\">\n          <input type=\"text\" placeholder=\"添加一条待办\" />\n          <button>添加任务</button>\n        </div>\n        <ul class=\"todo-list\">\n          <li>示例任务</li>\n        </ul>\n      </section>\n    </main>\n  </body>\n</html>\n",
      },
      {
        path: "styles.css",
        language: "css",
        content:
          "body {\n  margin: 0;\n  font-family: Arial, sans-serif;\n  background: #f8f8fb;\n}\n\n.todo-page {\n  min-height: 100vh;\n  display: grid;\n  place-items: center;\n}\n\n.todo-card {\n  width: min(92vw, 480px);\n  padding: 24px;\n  border-radius: 18px;\n  background: white;\n}\n",
      },
    ],
    config: {
      editableFiles: [
        {
          path: "index.html",
          language: "html",
          content:
            "<!DOCTYPE html>\n<html lang=\"zh-CN\">\n  <head>\n    <meta charset=\"UTF-8\" />\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n    <title>待办事项面板</title>\n    <link rel=\"stylesheet\" href=\"styles.css\" />\n  </head>\n  <body>\n    <main class=\"todo-page\">\n      <section class=\"todo-card\">\n        <h1>待办事项</h1>\n        <div class=\"composer\">\n          <input type=\"text\" placeholder=\"添加一条待办\" />\n          <button>添加任务</button>\n        </div>\n        <ul class=\"todo-list\">\n          <li>示例任务</li>\n        </ul>\n      </section>\n    </main>\n  </body>\n</html>\n",
        },
        {
          path: "styles.css",
          language: "css",
          content:
            "body {\n  margin: 0;\n  font-family: Arial, sans-serif;\n  background: #f8f8fb;\n}\n\n.todo-page {\n  min-height: 100vh;\n  display: grid;\n  place-items: center;\n}\n\n.todo-card {\n  width: min(92vw, 480px);\n  padding: 24px;\n  border-radius: 18px;\n  background: white;\n}\n",
        },
      ],
      requirements: [
        "页面中包含标题、输入框、添加按钮和待办列表。",
        "面板区域应有明确的卡片容器和基本留白。",
        "列表中至少存在一条示例任务，便于展示结构完整性。",
      ],
      requiredSelectors: [".composer", ".todo-list", "button"],
      requiredTexts: ["待办事项", "添加任务"],
      evaluationRules: [
        {
          id: "todo-required-file-html",
          title: "保留 HTML 入口文件",
          description: "提交中需要包含 index.html，保证页面可被评测系统加载。",
          engine: "static",
          type: "file",
          dimension: "engineering",
          target: "index.html",
          failureSeverity: "error",
          failureScoreImpact: -10,
          successMessage: "已找到 index.html，可继续进行结构与渲染检查。",
          failureMessage: "缺少 index.html，评测系统无法定位页面入口。",
        },
        {
          id: "todo-required-file-css",
          title: "保留样式文件",
          description: "提交中需要包含 styles.css，以便评估页面样式和布局。",
          engine: "static",
          type: "file",
          dimension: "engineering",
          target: "styles.css",
          failureSeverity: "error",
          failureScoreImpact: -8,
          successMessage: "已找到 styles.css，样式检查可正常进行。",
          failureMessage: "缺少 styles.css，页面样式和布局将无法完整评估。",
        },
        {
          id: "todo-selector-composer",
          title: "存在输入操作区",
          description: "源码中应包含 .composer 容器，用于组织输入框和按钮。",
          engine: "static",
          type: "selector",
          dimension: "correctness",
          target: ".composer",
          failureSeverity: "warning",
          failureScoreImpact: -8,
          successMessage: "源码中已包含输入操作区。",
          failureMessage: "源码中未找到 .composer，输入区结构不完整。",
        },
        {
          id: "todo-selector-list",
          title: "存在待办列表",
          description: "源码中应包含 .todo-list 列表容器。",
          engine: "static",
          type: "selector",
          dimension: "correctness",
          target: ".todo-list",
          failureSeverity: "warning",
          failureScoreImpact: -8,
          successMessage: "源码中已包含待办列表容器。",
          failureMessage: "源码中未找到 .todo-list，任务展示区域缺失。",
        },
        {
          id: "todo-text-title",
          title: "显示页面标题",
          description: "页面中应出现“待办事项”文字。",
          engine: "render",
          type: "text",
          dimension: "uiRendering",
          target: "待办事项",
          failureSeverity: "warning",
          failureScoreImpact: -6,
          successMessage: "页面渲染后已显示标题。",
          failureMessage: "页面渲染后未显示“待办事项”标题。",
        },
        {
          id: "todo-text-button",
          title: "显示添加按钮文案",
          description: "页面中应出现“添加任务”按钮文案。",
          engine: "render",
          type: "text",
          dimension: "correctness",
          target: "添加任务",
          failureSeverity: "warning",
          failureScoreImpact: -6,
          successMessage: "页面渲染后已显示添加按钮文案。",
          failureMessage: "页面渲染后未显示“添加任务”按钮文案。",
        },
        {
          id: "todo-render-button",
          title: "浏览器中存在按钮元素",
          description: "渲染后的 DOM 中应存在按钮元素。",
          engine: "render",
          type: "selector",
          dimension: "uiRendering",
          target: "button",
          failureSeverity: "warning",
          failureScoreImpact: -5,
          successMessage: "浏览器渲染后的 DOM 中已检测到按钮元素。",
          failureMessage: "浏览器渲染后的 DOM 中未检测到按钮元素。",
        },
        {
          id: "todo-layout-keyword",
          title: "包含基础布局样式",
          description: "样式中建议体现基础布局能力，例如 display/grid/flex。",
          engine: "static",
          type: "keyword",
          dimension: "codeQuality",
          keywords: ["display", "place-items"],
          failureSeverity: "warning",
          failureScoreImpact: -6,
          successMessage: "样式中已包含基础布局声明。",
          failureMessage: "样式中缺少明确的布局声明，面板位置可能不稳定。",
        },
        {
          id: "todo-console-clean",
          title: "浏览器运行期无报错",
          description: "页面加载后不应出现 console error 或 page error。",
          engine: "render",
          type: "console",
          dimension: "engineering",
          failureSeverity: "warning",
          failureScoreImpact: -6,
          successMessage: "浏览器控制台未捕获到运行期错误。",
          failureMessage: "浏览器控制台存在运行期错误，说明页面稳定性仍需提升。",
        },
      ],
      renderConfig: {
        viewportWidth: 1440,
        viewportHeight: 960,
        waitAfterLoadMs: 250,
      },
      weights: {
        correctness: 35,
        codeQuality: 20,
        uiRendering: 25,
        engineering: 20,
      },
    },
  },
];
